import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ImageCrawlForm from '@/components/ImageCrawlForm'
import { useState } from 'react'
import { ApiResponse } from './api/crawl'
import MostFrequentWords from '@/components/MostFrequentWords'
import Gallery from '@/components/Gallery'
import CrawlInfo from '@/components/CrawlInfo'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [crawlApiResponse, setCrawlApiResponse] = useState<ApiResponse>();

  const handleFormSubmit = (url: string, token: string) => {
    fetch('/api/crawl', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ url, token }),
    })
      .then((response) => response.json())
      .then((data: ApiResponse) => setCrawlApiResponse(data))
      .catch((error) => setCrawlApiResponse({success: false, message: error.message} as ApiResponse));
  };

  return (
    <>
      <Head>
        <title>Simple Image Crawler</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div className='p-6'>
          <ImageCrawlForm onSubmit={handleFormSubmit} />

          {crawlApiResponse?.success && crawlApiResponse.data ? (
            <>
              <Gallery images={crawlApiResponse.data.images} />
              <MostFrequentWords wordCount={crawlApiResponse?.data?.wordCount || 0} topWords={crawlApiResponse?.data?.mostFrequentWords} />
            </>
          ) : crawlApiResponse && !crawlApiResponse.success &&  (
            <CrawlInfo message={crawlApiResponse?.message || 'error'} />
          )}
        </div>

      </main>
    </>
  )
}
